#CONFIGURACION DE GATEWAY-SERVICE
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: usuarios-service
          uri: lb://USUARIOS-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: motos-service
          uri: lb://MOTOS-SERVICE
          predicates:
            - Path=/api/motos/**
          filters:
            - StripPrefix=2

        - id: carros-service
          uri: lb://CARROS-SERVICE
          predicates:
            - Path=/api/carros/**
          filters:
            - StripPrefix=2
