# SERVIDOR DE CONFIGURACION (CONFIG-SERVER)
server:
  port: 8090
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/ervintrianodev/microservices-spring-y
          search-paths:
          - config-data

  application:
    name: config-service